version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000
             celery -A news worker --loglevel=info
             celery -A news beat --loglevel=info
            "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  migration:
    image: postgres
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db
  celery:
    build: .
    command: celery -A news worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
  celery-beat:
    build: .
    command: celery -A news beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
