# Generated by Django 3.2.6 on 2021-08-28 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('pubDate', models.DateTimeField(null=True)),
                ('description', models.TextField(null=True)),
                ('link', models.CharField(max_length=200)),
                ('keyword', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.keywords')),
            ],
        ),
    ]
