# Generated by Django 3.2.6 on 2021-08-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keywords',
            new_name='Keyword',
        ),
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
